<a href="https://colab.research.google.com/github/vishwakarma9470/Machine_Learning_Algorithms_-_Projects/blob/main/Logistic_Regression_For_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
dataset.head()

AttributeError: head

In [4]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [9]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [10]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [11]:
df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3
149,5.9,3.0,5.1,1.8


In [12]:
## independent and dependent features


In [13]:
x = df
y = dataset.target

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
x

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [16]:
df['target']=dataset.target

In [17]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [18]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
## Binary classification
df[df['target']!=2]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


In [21]:
df_copy = df[df['target']!=2]

In [22]:
df_copy

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


In [32]:
## independent and dependent features
X = df_copy.iloc[:, :-1]
Y = df_copy.iloc[:, -1]

In [33]:
from sklearn.linear_model import LogisticRegression



In [38]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [39]:
classifier = LogisticRegression()

In [40]:
classifier.fit(X_train, Y_train)

LogisticRegression()

In [47]:
classifier.predict_proba(X_test)

array([[0.00118455, 0.99881545],
       [0.01579803, 0.98420197],
       [0.00304709, 0.99695291],
       [0.96959941, 0.03040059],
       [0.94269372, 0.05730628],
       [0.97161144, 0.02838856],
       [0.99356322, 0.00643678],
       [0.0316902 , 0.9683098 ],
       [0.97460702, 0.02539298],
       [0.9789308 , 0.0210692 ],
       [0.95512884, 0.04487116],
       [0.96072669, 0.03927331],
       [0.00430743, 0.99569257],
       [0.98586374, 0.01413626],
       [0.00927792, 0.99072208],
       [0.98146423, 0.01853577],
       [0.00207948, 0.99792052],
       [0.00125531, 0.99874469],
       [0.97461564, 0.02538436],
       [0.96116169, 0.03883831]])

In [48]:
classifier.predict_log_proba(X_test)

array([[-6.73838873e+00, -1.18525639e-03],
       [-4.14786972e+00, -1.59241538e-02],
       [-5.79356697e+00, -3.05174573e-03],
       [-3.08722670e-02, -3.49329343e+00],
       [-5.90138414e-02, -2.85934508e+00],
       [-2.87993072e-02, -3.56176904e+00],
       [-6.45758144e-03, -5.04572748e+00],
       [-3.45174793e+00, -3.22031972e-02],
       [-2.57209491e-02, -3.67328239e+00],
       [-2.12943232e-02, -3.85994302e+00],
       [-4.59090405e-02, -3.10395992e+00],
       [-4.00653119e-02, -3.23721013e+00],
       [-5.44741281e+00, -4.31673818e-03],
       [-1.42371304e-02, -4.25901203e+00],
       [-4.68011806e+00, -9.32122648e-03],
       [-1.87097142e-02, -3.98805269e+00],
       [-6.17563921e+00, -2.08164138e-03],
       [-6.68037306e+00, -1.25609814e-03],
       [-2.57121041e-02, -3.67362193e+00],
       [-3.96126322e-02, -3.24834815e+00]])

In [41]:
## prediction
Y_pred = classifier.predict(X_test)

In [42]:
Y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [43]:
## confusion matrix, accuracy score, classification report

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [46]:
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))
print(classification_report(Y_pred, Y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [49]:
## Hyperparameter Tuning


In [50]:
## GridsearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [53]:
parameters = {'penalty':['l1', 'l2', 'elasticnet', None], 'C':[1,10,20] }

In [55]:
clf = GridSearchCV(classifier, param_grid=parameters, cv=5, scoring='accuracy')

In [56]:
## spliting of train data to validation data
clf.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ['l1', 'l2', 'elasticnet', None]},
             scoring='accuracy')

In [57]:
clf.best_estimator_

LogisticRegression(C=1)

In [58]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [59]:
clf.best_score_

np.float64(1.0)

In [60]:
classifier = LogisticRegression(C=1, penalty='l2')

In [66]:
classifier = LogisticRegression(C=1, penalty='l2')
classifier.fit(X_train, Y_train)

LogisticRegression(C=1)

In [67]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))
print(classification_report(Y_pred, Y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [68]:
## Randomized searchCV
from sklearn.model_selection import RandomizedSearchCV

In [69]:
random_clf = RandomizedSearchCV(classifier, param_distributions=parameters, cv=5, scoring='accuracy')

In [70]:
random_clf.fit(X_train, Y_train )

RandomizedSearchCV(cv=5, estimator=LogisticRegression(C=1),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    None]},
                   scoring='accuracy')

In [71]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}

In [72]:
## Logistic regression create and check accuracy

In [75]:
classifier = LogisticRegression(C=1, penalty='l2')

In [76]:
classifier = LogisticRegression(C=1, penalty='l2')
classifier.fit(X_train, Y_train)

LogisticRegression(C=1)

In [77]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test, Y_pred))
print(accuracy_score(Y_test, Y_pred))
print(classification_report(Y_pred, Y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

